name: Download ics file

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */3 * * *"

jobs:
  download-ics:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: dist # Replace 'dist' with the folder containing your built static files

      - name: Download ICS file
        run: curl -o dist/basic.ics https://calendar.google.com/calendar/ical/finos.org_fac8mo1rfc6ehscg0d80fi8jig%40group.calendar.google.com/public/basic.ics

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: dist # Replace 'dist' with the folder containing your built static files
